### PR TITLE
Create/upgrade GCP documentation to new format #16

### PR DESCRIPTION
**Pull request by frbaroni**

### CODE REVIEW

**Comment by masterleros** [comment]
Cool Fernando!! thanks for this!
It's missing to compile the documentation so that it's updated in the repo. for that you can execute "build-doc.sh" at the root folder, so that it will generate the .md for your documentation update

**Comment by frbaroni** [comment]
Hello Leo,
Generated docs and updated PR :)

Thanks!

**Comment by masterleros** [comment]
WOW, tons of functions documentation! 👍 
Please check the generated doc, it seems that there are some inconsistencies that need to be fixed (e.j: functions must use ( ) at the end):
https://github.com/masterleros/bash-devops-libs/blob/feature/16-gcp-documentation/docs/gcp.md

**Comment by frbaroni** [comment]
Ok, so, added () to all functions and changed syntax for optional from [$optional] to $[optiona], should be ok now :)

**Review by masterleros — APPROVED** [review]

**Pull request merged**
